SHELL=/bin/bash
CC=gcc
OUT64=nat_conf64
SRCS=$(wildcard *.c)
OBJS64=$(SRCS:%.c=%64.o)
#LIBS=-pthread
#CFLAGS=-I../include -O2 -static
#CFLAGS=-I../include -O2

.PHONY: clean exec

all: $(OUT64)

$(OUT64): $(OBJS64)
	@echo "  BUILD $(OUT64)"
	@$(CC) $(CFLAGS) $(OBJS64) -m64 $(LIBS) -o $(OUT64)

%64.o: %.c
	@echo "  CC    $<"
	@$(CC) $(CFLAGS) -m64 -c $< -o $@ -Wall

exec: $(OBJS64)
	$(CC) $(OBJS64) $(LIBS) -o $(OUT64)

clean:
	rm -f $(OBJS64)
	rm -f $(OUT64)
