SUBDIRS=$(wildcard */)
CLEANDIRS=$(SUBDIRS:%=clean-%)

.PHONY: subdirs $(SUBDIRS)
.PHONY: clean

subdirs: $(SUBDIRS)

$(SUBDIRS):
	@$(MAKE) -C $@ -f Makefile.m32

clean: $(CLEANDIRS)

$(CLEANDIRS):
	@$(MAKE) -C $(@:clean-%=%) -f Makefile.m32 clean
